using System.Collections.Generic;
using System.Linq;

namespace WordQuest
{
    /// <summary>All word lists. Twelve categories; each one has its own collection and progress bar.</summary>
    public static class WordBank
    {
        public class Category
        {
            public string Id, Name, ArtKey;
            public string[] Words;
        }

        static readonly string[][] Data =
        {
            new[] { "Animals", "CAT DOG PIG COW HEN FOX BAT RAT OWL APE EEL ANT BEE ELK YAK EMU RAM LION BEAR DEER GOAT DUCK FROG WOLF SEAL MOLE CRAB TOAD LAMB MULE HAWK DOVE SWAN MOTH FISH KIWI LYNX ORCA TIGER HORSE SHEEP ZEBRA EAGLE SNAKE MOUSE RABBIT WHALE SHARK CAMEL PANDA KOALA OTTER LLAMA HIPPO BISON MONKEY DONKEY TURTLE PARROT BEAVER BADGER FERRET GIRAFFE DOLPHIN PENGUIN GORILLA LEOPARD OSTRICH PEACOCK LOBSTER SQUIRREL CHEETAH RACCOON KANGAROO HAMSTER BUTTERFLY ELEPHANT CROCODILE FLAMINGO PORCUPINE WALRUS GECKO LIZARD SPIDER" },
            new[] { "Food", "PIE JAM EGG HAM TEA NUT FIG PEA RICE CAKE MILK BEAN CORN SOUP TACO KALE LIME PEAR PLUM DATE MEAT BREAD PIZZA PASTA SALAD APPLE MANGO LEMON GRAPE BERRY HONEY BACON BAGEL CANDY CREAM CURRY DONUT FRIES JUICE MELON OLIVE ONION PEACH PEPPER BANANA BURGER CEREAL COOKIE ORANGE POTATO TOMATO YOGURT CARROT CHEESE NOODLE PANCAKE WAFFLE PRETZEL SANDWICH MUFFIN COCONUT AVOCADO PUMPKIN CHICKEN BROCCOLI SPAGHETTI CHOCOLATE STRAWBERRY BLUEBERRY MUSHROOM CUCUMBER LETTUCE SPINACH NACHOS BURRITO SAUSAGE BUTTER SUGAR" },
            new[] { "Places", "ROME PARIS LIMA OSLO CAIRO DELHI TOKYO DUBAI SEOUL LONDON MADRID BERLIN VIENNA PRAGUE MOSCOW SYDNEY TORONTO BEIJING LISBON ATHENS DUBLIN BRAZIL CANADA FRANCE GREECE INDIA ITALY JAPAN KENYA MEXICO NEPAL PERU SPAIN TURKEY CHINA EGYPT CUBA CHILE IRAN IRAQ OMAN QATAR GHANA HAITI JORDAN NIGER SUDAN TONGA YEMEN ISRAEL POLAND NORWAY SWEDEN FINLAND IRELAND ICELAND GERMANY AUSTRIA BELGIUM ENGLAND SCOTLAND HOLLAND MOROCCO ARGENTINA AUSTRALIA THAILAND VIETNAM SINGAPORE PORTUGAL HUNGARY ALASKA TEXAS HAWAII BOSTON DENVER MIAMI" },
            new[] { "Sports", "GOLF POLO JUDO RUGBY TENNIS SOCCER HOCKEY CRICKET BOXING RACING ROWING SKIING SURFING DIVING ARCHERY FENCING KARATE BOWLING SQUASH CURLING SKATING SPRINT MARATHON JAVELIN HURDLES SAILING CYCLING DARTS YOGA SWIM RUN JUMP KICK GOAL BALL BAT NET PUCK CLUB TEAM COACH MATCH SCORE MEDAL TROPHY RACKET HELMET CAPTAIN PLAYER LEAGUE STADIUM REFEREE CHAMPION WRESTLING BASKETBALL BASEBALL FOOTBALL VOLLEYBALL BADMINTON GYMNASTICS SNOWBOARD CLIMBING HANDBALL WHISTLE PENALTY DEFENDER GOALIE STRIKER TRACK RELAY" },
            new[] { "Space", "SUN MOON STAR MARS VENUS EARTH COMET ORBIT ROCKET PLANET GALAXY METEOR SATURN JUPITER URANUS PLUTO MERCURY NEPTUNE COSMOS ALIEN ASTEROID NEBULA SHUTTLE SATELLITE TELESCOPE ECLIPSE GRAVITY LUNAR SOLAR SPACE COSMIC PROBE ROVER CRATER ASTRONAUT UNIVERSE STARDUST LAUNCH CAPSULE STATION HORIZON SUPERNOVA QUASAR PULSAR BLACKHOLE ZODIAC ORBITER LANDER SPACESHIP MISSION COUNTDOWN CONSTELLATION" },
            new[] { "Nature", "TREE LEAF ROSE RAIN SNOW WIND ROCK HILL LAKE POND MOSS FERN SEED ROOT BUSH GRASS FLOWER RIVER OCEAN BEACH CLOUD STORM FOREST MEADOW VALLEY CANYON DESERT ISLAND JUNGLE MOUNTAIN SUNSHINE RAINBOW THUNDER BREEZE BLOSSOM PEBBLE WATERFALL VOLCANO GLACIER TULIP DAISY LILY PINE OAK MAPLE WILLOW CACTUS BAMBOO ORCHID SPROUT PETAL BRANCH TWIG DEW FROST FOG MIST DUSK DAWN SUNSET SUNRISE HARVEST GARDEN STREAM SPRING SUMMER AUTUMN WINTER" },
            new[] { "Movies", "FILM ACTOR SCENE STAGE DRAMA COMEDY HORROR ACTION SCRIPT CAMERA DIRECTOR POPCORN TICKET CINEMA SCREEN TRAILER SEQUEL HERO VILLAIN STUNT CLIP CAST CREW STAR ROLE PLOT SET LENS PRODUCER FANTASY THRILLER ROMANCE MUSICAL COSTUME EDITOR OSCAR PREMIERE SOUNDTRACK ANIMATION SCREENPLAY CLASSIC EFFECTS DIALOGUE CREDITS MATINEE ACTRESS STUDIO SCREENING CAMEO MOVIE SEAT CURTAIN" },
            new[] { "Technology", "CODE DATA WIFI APP WEB BYTE CHIP USER FILE LINK MENU ICON MOUSE PHONE ROBOT LAPTOP SCREEN CLOUD EMAIL ONLINE CURSOR SERVER PIXEL ROUTER BROWSER KEYBOARD MONITOR NETWORK PROGRAM SOFTWARE HARDWARE INTERNET DOWNLOAD PASSWORD DATABASE SMARTPHONE TABLET CAMERA DRONE SENSOR BATTERY CHARGER SPEAKER PRINTER SCANNER STREAM UPLOAD BLUETOOTH ALGORITHM PROCESSOR BINARY DIGITAL VIRTUAL GADGET" },
            new[] { "Music", "SONG NOTE BAND DRUM HARP TUNE BEAT BASS RHYTHM MELODY PIANO GUITAR VIOLIN FLUTE TRUMPET SINGER CHORUS LYRICS ALBUM CONCERT ORCHESTRA SAXOPHONE CLARINET CELLO OBOE TENOR ALTO OPERA JAZZ ROCK FOLK POP DISCO SOUL BLUES TEMPO SCALE CHORD TREBLE HARMONY RECORD MICROPHONE GUITARIST DRUMMER SONGBIRD LULLABY ANTHEM BALLAD SOLO DUET" },
            new[] { "Body", "HEAD HAND FOOT ARM LEG EYE EAR NOSE MOUTH HAIR NECK BACK KNEE ELBOW WRIST ANKLE FINGER THUMB TOES SKIN BONE HEART BRAIN LUNG LIVER KIDNEY STOMACH MUSCLE SHOULDER CHEST BELLY THROAT TONGUE TEETH TOOTH LIP CHIN CHEEK BROW FOREHEAD SKULL SPINE RIBS HIP PALM NAIL BLOOD VEIN PULSE BREATH SKELETON EYEBROW EYELASH SENSE TASTE SMELL HEARING NERVE JOINT ARTERY" },
            new[] { "Ocean", "FISH SHARK WHALE CRAB SEAL EEL WAVE TIDE REEF SAND SHELL CORAL PEARL BOAT SHIP ANCHOR DOLPHIN OCTOPUS SQUID LOBSTER SHRIMP TURTLE SEAHORSE JELLYFISH STARFISH ORCA PIRATE TREASURE HARBOR ISLAND BEACH SAILOR CAPTAIN LIGHTHOUSE SEAWEED PLANKTON URCHIN MERMAID CURRENT SURF FOAM SPRAY NAVY DEEP SALT DIVER SUBMARINE PADDLE MARLIN SALMON TUNA COD KRILL CLAM OYSTER MUSSEL WALRUS PENGUIN" },
            new[] { "History", "KING QUEEN CROWN CASTLE KNIGHT SWORD SHIELD EMPIRE ROMAN VIKING PHARAOH PYRAMID TEMPLE ANCIENT MEDIEVAL TREATY BATTLE ARMY WAR PEACE TRIBE REBEL REVOLT THRONE PALACE DYNASTY ARCHER SCROLL RUINS ARTIFACT FOSSIL MUSEUM HISTORY LEGEND MYTH ERA AGE TOMB MUMMY GLADIATOR EXPLORER COLONY SETTLER PIONEER PRINCE PRINCESS EMPEROR SULTAN SAMURAI SPARTAN TROJAN PILGRIM MONUMENT" },
        };

        static Category[] all;

        public static Category[] All
        {
            get
            {
                if (all != null) return all;
                all = new Category[Data.Length];
                for (int i = 0; i < Data.Length; i++)
                {
                    var words = Data[i][1].Split(' ')
                        .Select(w => w.Trim().ToUpperInvariant())
                        .Where(w => w.Length >= 3 && w.Length <= 10 && w.All(c => c >= 'A' && c <= 'Z'))
                        .Distinct().ToArray();
                    all[i] = new Category { Id = Data[i][0].ToLowerInvariant(), Name = Data[i][0], ArtKey = "cat_" + i, Words = words };
                }
                return all;
            }
        }

        public static Category Get(int i) => All[((i % All.Length) + All.Length) % All.Length];
        public static int Count => All.Length;
    }
}
